services:
  backend:
    image: golang:1.22
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - go_modules:/go/pkg/mod
    environment:
      - GIN_MODE=debug
      - CGO_ENABLED=1
    working_dir: /app
    command: |
      sh -c "
        go mod download &&
        go install github.com/cosmtrek/air@v1.49.0 &&
        air
      "
    networks:
      - app-network

  frontend:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    working_dir: /app
    command: |
      sh -c "
        npm install &&
        npm run dev
      "
    networks:
      - app-network

volumes:
  go_modules:
  node_modules:

networks:
  app-network:
    driver: bridge